Create small thumbnails when taking the photo so to save memory
ubclaunchpad/LaunchNote pull request #50
Opened 2018-02-11 06:23 UTC by vpineda1996

Multiple fixes in this commit ( fixes #49 )

- Remove files that were created (previously we only deleted the entry from the db)
- PnR stuff related on how we load images
- Database change: now we store a thumbnail that gets loaded into the recyclerView

RAM usage drops to around 60 MB with 30 images loaded to all of the 3 fragments.
Butter smooth animations on my phone 👍

2018-02-15 20:25 UTC, frostyshadows requested changes
Tested it out and the RAM usage is much better now,
 great work! 👍 Left a few comments.

2018-02-15 20:25 UTC, frostyshadows commented on app/src/main/java/com/example/ubclaunchpad/launchnote/addPhoto/TakePhotoActivity.kt
> +import java.util.*
You generally don't want to do * imports in Java. [Stackoverflow link](https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad) if you're interested.

2018-02-15 20:25 UTC, frostyshadows commented on app/src/main/java/com/example/ubclaunchpad/launchnote/addPhoto/TakePhotoActivity.kt
> +                    if (out != null) {
You can just write `out?.close()`

2018-02-15 20:25 UTC, frostyshadows commented on app/src/main/java/com/example/ubclaunchpad/launchnote/addPhoto/TakePhotoActivity.kt
> +    private fun createImageFile(forCompressed: Boolean = false): File {
add more documentation/comments

2018-02-15 20:25 UTC, frostyshadows commented on app/src/main/java/com/example/ubclaunchpad/launchnote/photoBrowser/AllPhotosAdapter.kt
> +
remove extra spaces

2018-02-15 23:51 UTC, vpineda1996 commented
fixes #47

2018-02-16 21:26 UTC, frostyshadows approved these changes

2018-02-16 22:36 UTC, merged