YL-29-save2Camera
ubclaunchpad/LaunchNote pull request #63
Opened 2018-03-10 22:04 UTC by yvonneli7

2018-03-17 18:56 UTC, daphliu-zz reviewed
Saving works well in regular screen mode but it should also be able to save the image in full screen mode too.

2018-03-24 17:55 UTC, frostyshadows requested changes
Looks good, just a minor comment. Daphne made a comment too.

2018-03-24 17:55 UTC, frostyshadows commented on app/src/main/java/com/example/ubclaunchpad/launchnote/photoBrowser/AllPhotosFragment.kt
> +                Flowable.fromCallable {
Please make the indents 2 spaces instead of 4, and add some comments for documentation to explain what you did.

2018-03-24 18:26 UTC, vpnda requested changes

2018-03-24 18:26 UTC, vpineda1996 commented on app/src/main/java/com/example/ubclaunchpad/launchnote/photoBrowser/AllPhotosFragment.kt
> +                                                MediaStore.Images.Media.insertImage(activity.getContentResolver(), bitmap , "yourTitle", "yourDescription");
So many indents, would you mind breaking it down to smaller functions. I think you can define them inside saveSelection

2018-03-24 21:50 UTC, vpnda approved these changes

2018-04-16 04:38 UTC, frostyshadows approved these changes

2018-05-26 21:22 UTC, merged